language: java
install: true
jdk:
  - openjdk8
  - openjdk11
os:
  - linux
cache:
  directories:
  - $HOME/.gradle
  - $HOME/.m2/repository
before_script:
  - echo "MAVEN_OPTS='-Xmx512m'" > ~/.mavenrc
script:
  - mvn clean install -U
  - cd example-project
  - mvn clean install -U
  - cd ../example-project-gradle
  - ./gradlew clean build